[package]
name = "aoc_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
criterion = "0.4.0"
futures = "0.3.25"
itertools = "0.10.5"
lazy_static = "1.4.0"
serde = "1.0.130"
